### ISSUE TITLE
Multi user problem : RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by appcilious** [FarjaalAhmad/django_bgRemoverML#25]
If there are multiple users using the site, the process crashes and resumes with 

```
Exception happened during processing of request from ('xxx.xxx.xxx.xxx', 13787)
Traceback (most recent call last):
File "/usr/lib64/python3.6/socketserver.py", line 320, in _handle_request_noblock
self.process_request(request, client_address)
File "/usr/lib64/python3.6/socketserver.py", line 669, in process_request
t.start()
File "/usr/lib64/python3.6/threading.py", line 846, in start
_start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

The XXX.XXX.XXX.XXX is the IP address of the user.

**Comment by FarjaalAhmad** [comment]
Hey, can you please show a more descriptive error as this shows nothing?

**Comment by appcilious** [comment]
This was the entire error message. I traced the problem to the inability of the process to spawn more threads. I solved it by increasing the limit of threads the user can spawn.

**Comment by FarjaalAhmad** [comment]
Sure, I'm closing this issue.
