### ISSUE TITLE
IT IS SHUTTING DOWN

### ISSUE THREAD

**Issue by haardparmar** [FarjaalAhmad/django_bgRemoverML#4]
When I open 127.0.0.1, it displays the input form page, but after we submit an image, Django automatically shuts down and webpage shows - "This site can't be reached". BTW, the same code is working in my another PC.

PLEASE HELP

**Comment by saadtanoli** [comment]
Please show the screenshot of he django running on command-line when it closes? and please specify your python version and OS info

**Comment by FarjaalAhmad** [comment]
Please show the screenshot of he django running on command-line when it closes? and please specify your python version and OS info

**Comment by haardparmar** [comment]
![Screenshot from 2020-11-14 12-52-10](https://user-images.githubusercontent.com/71481567/99142167-a28cce80-2678-11eb-98a3-516555fadbad.png)


**python version - 3.8.5**

**OS : ubuntu 20.04 LTS**

I have same PC with same OS and python version, it that, it works as it should be (I mean it works great).

**EAGERLY WAITING FOR YOUR REPLY**


The code I use to upload image to django is : 

```
import requests
import base64
with open("image/location", "rb") as image_file:
    encoded_string = base64.b64encode(image_file.read())
    data = {'image':encoded_string}
    z = requests.post("http://37521316da96.in.ngrok.io/upload", data=data)
    a=z.content
    print(a)
```

I have put **37521316da96.in.ngrok.io** in allowed hosts

**Comment by FarjaalAhmad** [comment]
is the code working fine when you upload image from localhost:8000?

**Comment by haardparmar** [comment]
No

**Comment by FarjaalAhmad** [comment]
It seems like there is some work to do on the API thing. I'll try myself and commit the changes.

**Comment by haardparmar** [comment]
wait
i am trying reinstalling my OS

**Comment by haardparmar** [comment]
Then i will tell you

**Comment by FarjaalAhmad** [comment]
no, you don't need to reinstall your os. I've haven't done much work on API. I think there is the problem not in your os

**Comment by haardparmar** [comment]
Can you doo one thing, can you make it in flask?

**Comment by haardparmar** [comment]
I need you project as soon as possible

**Comment by FarjaalAhmad** [comment]
> Can you doo one thing, can you make it in flask?

Nah, I've only code django not flask

**Comment by haardparmar** [comment]
okay

**Comment by haardparmar** [comment]
so, can you do it faster... please

**Comment by haardparmar** [comment]
I dont think that there is some error in you code...

it works great in my another PC

**Comment by haardparmar** [comment]
I'll format my PC (in which it is not working) and i'll tell you

**Comment by haardparmar** [comment]
Done brother, 
there was an error in numpy, now it's working fine

**Comment by FarjaalAhmad** [comment]
No worries 👍🏼

**Comment by RiddhishWisdomlogix** [comment]
i have same issue can you tell me the version of numpy which is suitable for this

**Comment by RiddhishWisdomlogix** [comment]
> Done brother, there was an error in numpy, now it's working fine

i have same issue can you please share the solution
