### ISSUE TITLE
select gpu?

### ISSUE THREAD

**Issue by kamikazem** [FarjaalAhmad/django_bgRemoverML#6]
i managed to run your project on my win10 laptop which has two gpus,
but the question is how should i specify using my second gpu for ml ? currently it seems like it's using cpu and takes too long(25 seconds for a 310x453 pixels picture).

+thanks for your awesome project ,ive been searching for this for about a year...

**Comment by FarjaalAhmad** [comment]
Actually I don't had gpu but have good cpu, so I used the tensorflow-cpu one.
Try tensorflow-gpu one, I hope it works fine :)

**Comment by kamikazem** [comment]
what performance should i expect from a good cpu ?

**Comment by FarjaalAhmad** [comment]
I am not sure about that :/ but works fine though!
