### ISSUE TITLE
requirements.txt seems to have alot more dependies than required!

### ISSUE THREAD

**Issue by Naman-Monga** [FarjaalAhmad/django_bgRemoverML#7]
Does the project really requires all those dependencies? If not, it would be great if you could filter out the ones not used...

**Comment by FarjaalAhmad** [comment]
Hey!
As to my knowledge, the sub-dependencies are also included into the requrements.txt file. Like, dependencies of tensorflow are also included into the file. If you think that there is some dependencies which are not used, make a pull request, I'll check and merge it. Thanks for looking onto the project :)
