### ISSUE TITLE
Requirement Installation issue

### ISSUE THREAD

**Issue by deepak727** [FarjaalAhmad/django_bgRemoverML#9]
Hi,

I am trying to install your  project, but it seems there are some problem with the dependency version.

python3 -m pip install -r requirements.txt command gives me the below error.

The conflict is caused by:
    The user requested numpy==1.19.0
    gluoncv 0.7.0 depends on numpy
    h5py 2.10.0 depends on numpy>=1.7
    imageio 2.9.0 depends on numpy
    keras-preprocessing 1.1.2 depends on numpy>=1.9.1
    matplotlib 3.2.2 depends on numpy>=1.11
    mxnet 1.6.0 depends on numpy<2.0.0 and >1.16.0
    opencv-python 4.3.0.36 depends on numpy>=1.17.3
    opt-einsum 3.2.1 depends on numpy>=1.7
    pywavelets 1.1.1 depends on numpy>=1.13.3
    scikit-image 0.17.2 depends on numpy>=1.15.1
    scipy 1.4.1 depends on numpy>=1.13.3
    tensorboard 2.2.2 depends on numpy>=1.12.0
    tensorflow 2.2.1 depends on numpy<1.19.0 and >=1.16.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

Any Suggestion, I am using ubuntu server 18.04 and python 3.8.0

**Comment by FarjaalAhmad** [comment]
Sorry for the late reply, actually I saw this issue just now and replying right away.

Can you please specify your pip version? As long as I know, I've tested on multiple machines and didn't got the error a single time. (Windows are Exception)

**Comment by deepak727** [comment]
Hi @FarjaalAhmad 

apologies for late reply.

I am using pip 20.0.2 along with python 3.8 on Linux mint.

**Comment by FarjaalAhmad** [comment]
I'll try this one myself now from scratch. I haven't worked on this one for a long time. I'll update as soon as I test it.

**Comment by cnrblm** [comment]
There are some conficts with numpy 1.19.0 version. Numpy's 1.18.5 version is worked for me. I created a pull request.
